---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus_sbx:9090']

  - job_name: 'openobserve'
    static_configs:
      - targets: ['openobserve-sqlite:5080']
    metrics_path: /metrics

  - job_name: 'minio-cluster'
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets: ['openobserve-sqlite-minio:9000']

  - job_name: 'minio-bucket'
    metrics_path: /minio/v2/metrics/bucket
    scheme: http
    static_configs:
      - targets: ['openobserve-sqlite-minio:9000']

  - job_name: 'minio-node'
    metrics_path: /minio/v2/metrics/node
    scheme: http
    static_configs:
      - targets: ['openobserve-sqlite-minio:9000']

  - job_name: 'minio-resource'
    metrics_path: /minio/v2/metrics/resource
    scheme: http
    static_configs:
      - targets: ['openobserve-sqlite-minio:9000']


  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana_sbx:3000']

  - job_name: 'syslog-ng'
    static_configs:
      - targets: ['syslog-ng-exporter:9577']
    metrics_path: /metrics
