---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus_sbx:9090']

  - job_name: 'openobserve'
    static_configs:
      - targets: ['openobserve-sqlite:5080']

  - job_name: 'minio'
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['openobserve-sqlite-minio:9000']
